### ISSUE TITLE
Goal?

### ISSUE THREAD

**Issue by FrostKnight** [fleroviux/lunar#34]
Wondering what your goal is, is it to be similar to Noo-DS but focus more on stable releases and/or otther things?

Curious I am, watching this and at least* one other repo to see which turns out better. 

Hope all goes well

**Comment by fleroviux** [comment]
This is a just for fun project, as I clearly state at the start of the README.

<img width="875" alt="Bildschirm­foto 2023-06-06 um 21 56 38" src="https://github.com/fleroviux/lunar/assets/13669774/4ba27a46-200b-4d02-a5ba-74ed2cdcdb61">
